package com.wzy.mybatis.mapper;

import com.wzy.mybatis.domain.RunoobTbl;
import com.wzy.mybatis.domain.RunoobTblExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RunoobTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    long countByExample(RunoobTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    int deleteByExample(RunoobTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    int deleteByPrimaryKey(Integer runoobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    int insert(RunoobTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    int insertSelective(RunoobTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    List<RunoobTbl> selectByExample(RunoobTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    RunoobTbl selectByPrimaryKey(Integer runoobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") RunoobTbl record, @Param("example") RunoobTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    int updateByExample(@Param("record") RunoobTbl record, @Param("example") RunoobTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    int updateByPrimaryKeySelective(RunoobTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    int updateByPrimaryKey(RunoobTbl record);
}