package com.wzy.mybatis.mapper;

import com.wzy.mybatis.domain.TcountTbl;
import com.wzy.mybatis.domain.TcountTblExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TcountTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    long countByExample(TcountTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    int deleteByExample(TcountTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    int insert(TcountTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    int insertSelective(TcountTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    List<TcountTbl> selectByExample(TcountTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") TcountTbl record, @Param("example") TcountTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    int updateByExample(@Param("record") TcountTbl record, @Param("example") TcountTblExample example);
}