package com.wzy.mybatis.domain;

import java.util.Date;

public class RunoobTbl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runoob_tbl.runoob_id
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    private Integer runoobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runoob_tbl.runoob_title
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    private String runoobTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runoob_tbl.runoob_author
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    private String runoobAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runoob_tbl.submission_date
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    private Date submissionDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runoob_tbl.runoob_id
     *
     * @return the value of runoob_tbl.runoob_id
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public Integer getRunoobId() {
        return runoobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runoob_tbl.runoob_id
     *
     * @param runoobId the value for runoob_tbl.runoob_id
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public void setRunoobId(Integer runoobId) {
        this.runoobId = runoobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runoob_tbl.runoob_title
     *
     * @return the value of runoob_tbl.runoob_title
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public String getRunoobTitle() {
        return runoobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runoob_tbl.runoob_title
     *
     * @param runoobTitle the value for runoob_tbl.runoob_title
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public void setRunoobTitle(String runoobTitle) {
        this.runoobTitle = runoobTitle == null ? null : runoobTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runoob_tbl.runoob_author
     *
     * @return the value of runoob_tbl.runoob_author
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public String getRunoobAuthor() {
        return runoobAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runoob_tbl.runoob_author
     *
     * @param runoobAuthor the value for runoob_tbl.runoob_author
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public void setRunoobAuthor(String runoobAuthor) {
        this.runoobAuthor = runoobAuthor == null ? null : runoobAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runoob_tbl.submission_date
     *
     * @return the value of runoob_tbl.submission_date
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public Date getSubmissionDate() {
        return submissionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runoob_tbl.submission_date
     *
     * @param submissionDate the value for runoob_tbl.submission_date
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public void setSubmissionDate(Date submissionDate) {
        this.submissionDate = submissionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runoob_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", runoobId=").append(runoobId);
        sb.append(", runoobTitle=").append(runoobTitle);
        sb.append(", runoobAuthor=").append(runoobAuthor);
        sb.append(", submissionDate=").append(submissionDate);
        sb.append("]");
        return sb.toString();
    }
}