package com.wzy.mybatis.domain;

import java.util.ArrayList;
import java.util.List;

public class TcountTblExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public TcountTblExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRunoobAuthorIsNull() {
            addCriterion("runoob_author is null");
            return (Criteria) this;
        }

        public Criteria andRunoobAuthorIsNotNull() {
            addCriterion("runoob_author is not null");
            return (Criteria) this;
        }

        public Criteria andRunoobAuthorEqualTo(String value) {
            addCriterion("runoob_author =", value, "runoobAuthor");
            return (Criteria) this;
        }

        public Criteria andRunoobAuthorNotEqualTo(String value) {
            addCriterion("runoob_author <>", value, "runoobAuthor");
            return (Criteria) this;
        }

        public Criteria andRunoobAuthorGreaterThan(String value) {
            addCriterion("runoob_author >", value, "runoobAuthor");
            return (Criteria) this;
        }

        public Criteria andRunoobAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("runoob_author >=", value, "runoobAuthor");
            return (Criteria) this;
        }

        public Criteria andRunoobAuthorLessThan(String value) {
            addCriterion("runoob_author <", value, "runoobAuthor");
            return (Criteria) this;
        }

        public Criteria andRunoobAuthorLessThanOrEqualTo(String value) {
            addCriterion("runoob_author <=", value, "runoobAuthor");
            return (Criteria) this;
        }

        public Criteria andRunoobAuthorLike(String value) {
            addCriterion("runoob_author like", value, "runoobAuthor");
            return (Criteria) this;
        }

        public Criteria andRunoobAuthorNotLike(String value) {
            addCriterion("runoob_author not like", value, "runoobAuthor");
            return (Criteria) this;
        }

        public Criteria andRunoobAuthorIn(List<String> values) {
            addCriterion("runoob_author in", values, "runoobAuthor");
            return (Criteria) this;
        }

        public Criteria andRunoobAuthorNotIn(List<String> values) {
            addCriterion("runoob_author not in", values, "runoobAuthor");
            return (Criteria) this;
        }

        public Criteria andRunoobAuthorBetween(String value1, String value2) {
            addCriterion("runoob_author between", value1, value2, "runoobAuthor");
            return (Criteria) this;
        }

        public Criteria andRunoobAuthorNotBetween(String value1, String value2) {
            addCriterion("runoob_author not between", value1, value2, "runoobAuthor");
            return (Criteria) this;
        }

        public Criteria andRunoobCountIsNull() {
            addCriterion("runoob_count is null");
            return (Criteria) this;
        }

        public Criteria andRunoobCountIsNotNull() {
            addCriterion("runoob_count is not null");
            return (Criteria) this;
        }

        public Criteria andRunoobCountEqualTo(Integer value) {
            addCriterion("runoob_count =", value, "runoobCount");
            return (Criteria) this;
        }

        public Criteria andRunoobCountNotEqualTo(Integer value) {
            addCriterion("runoob_count <>", value, "runoobCount");
            return (Criteria) this;
        }

        public Criteria andRunoobCountGreaterThan(Integer value) {
            addCriterion("runoob_count >", value, "runoobCount");
            return (Criteria) this;
        }

        public Criteria andRunoobCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("runoob_count >=", value, "runoobCount");
            return (Criteria) this;
        }

        public Criteria andRunoobCountLessThan(Integer value) {
            addCriterion("runoob_count <", value, "runoobCount");
            return (Criteria) this;
        }

        public Criteria andRunoobCountLessThanOrEqualTo(Integer value) {
            addCriterion("runoob_count <=", value, "runoobCount");
            return (Criteria) this;
        }

        public Criteria andRunoobCountIn(List<Integer> values) {
            addCriterion("runoob_count in", values, "runoobCount");
            return (Criteria) this;
        }

        public Criteria andRunoobCountNotIn(List<Integer> values) {
            addCriterion("runoob_count not in", values, "runoobCount");
            return (Criteria) this;
        }

        public Criteria andRunoobCountBetween(Integer value1, Integer value2) {
            addCriterion("runoob_count between", value1, value2, "runoobCount");
            return (Criteria) this;
        }

        public Criteria andRunoobCountNotBetween(Integer value1, Integer value2) {
            addCriterion("runoob_count not between", value1, value2, "runoobCount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tcount_tbl
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 26 15:29:09 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}