package com.wzy.mybatis.domain;

public class TcountTbl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcount_tbl.runoob_author
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    private String runoobAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcount_tbl.runoob_count
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    private Integer runoobCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcount_tbl.runoob_author
     *
     * @return the value of tcount_tbl.runoob_author
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public String getRunoobAuthor() {
        return runoobAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcount_tbl.runoob_author
     *
     * @param runoobAuthor the value for tcount_tbl.runoob_author
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public void setRunoobAuthor(String runoobAuthor) {
        this.runoobAuthor = runoobAuthor == null ? null : runoobAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcount_tbl.runoob_count
     *
     * @return the value of tcount_tbl.runoob_count
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public Integer getRunoobCount() {
        return runoobCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcount_tbl.runoob_count
     *
     * @param runoobCount the value for tcount_tbl.runoob_count
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    public void setRunoobCount(Integer runoobCount) {
        this.runoobCount = runoobCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcount_tbl
     *
     * @mbg.generated Mon Nov 26 15:29:09 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", runoobAuthor=").append(runoobAuthor);
        sb.append(", runoobCount=").append(runoobCount);
        sb.append("]");
        return sb.toString();
    }
}